name: Build
on: [push]
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
      - name: Compile main.tex
        uses: dante-ev/latex-action@edge
        with:
          root_file: main.tex
          args: -outdir=out
      - name: Print folder structure
        run: tree
      - name: Upload main.pdf artifact
        uses: actions/upload-artifact@v3
        with:
          name: compiled-pdf
          path: out/main.pdf
