name: Build
on: [push]
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2

      - name: Compile main.tex
        uses: dante-ev/latex-action@edge
        with:
          root_file: main.tex

      - name: Upload compiled artifact
        uses: actions/upload-artifact@v3
        with:
          name: compiled
          path: main.pdf

  publish_to_heroku:
    runs-on: ubuntu-latest
    needs: build_latex
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2

      - name: Download artifact from previous job
        uses: actions/download-artifact@master
        with:
          name: compiled
          path: main.pdf

      - name: Move artifact to public folder
        run: mv ./main.pdf ./public/main-${{ github.sha }}.pdf

      - name: Publish to heroku
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "isetn-end-of-studies-project"
          heroku_email: "benna.anis2@gmail.com"
